// AutoGenerated file by RAGen (v1.1.0.124), (10/22/2011 19:43)

/*
 * Copyright 2010-11 Curt Binder
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __REEFANGEL_FEATURES_H__
#define __REEFANGEL_FEATURES_H__


//#define DateTimeSetup
//#define ATOSetup
//#define StandardLightSetup
//#define WavemakerSetup

//#define SIMPLE_MENU
#define DisplayLEDPWM
#define wifi
//#define RelayExp
//#define InstalledRelayExpansionModules  1
//#define PWMEXPANSION
#define VersionMenu
#define WDT
//#define CUSTOM_MENU
//#define CUSTOM_MENU_ENTRIES 6
//#define CUSTOM_MENU_ENTRIES 8
//#define CUSTOM_MAIN
//#define FONT_8x8
//#define FONT_8x16
//#define FONT_12x16
//#define NUMBERS_8x8
//#define NUMBERS_8x16
//#define NUMBERS_12x16
//#define NUMBERS_16x16
#define SALINITYEXPANSION
//#define RFEXPANSION
//#define AI_LED
#define IOEXPANSION
//
//#define __PLUS_SPECIAL_WIFI__

#endif  // __REEFANGEL_FEATURES_H__
